"""initial

Revision ID: 56f30a2bf485
Revises: 
Create Date: 2017-04-25 18:26:22.277652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f30a2bf485'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('pid', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('scontent', sa.Text(), nullable=True),
    sa.Column('date', sa.String(length=128), nullable=True),
    sa.Column('article_type', sa.String(length=128), nullable=True),
    sa.Column('tag', sa.String(length=128), nullable=True),
    sa.Column('view', sa.Integer(), nullable=True),
    sa.Column('url_from', sa.String(length=128), nullable=True),
    sa.Column('pic_count', sa.Integer(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('pid'),
    sa.UniqueConstraint('url_from')
    )
    op.create_index(op.f('ix_article_article_type'), 'article', ['article_type'], unique=False)
    op.create_index(op.f('ix_article_date'), 'article', ['date'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_article_date'), table_name='article')
    op.drop_index(op.f('ix_article_article_type'), table_name='article')
    op.drop_table('article')
    # ### end Alembic commands ###
